### 1. MENAMBAHKAN BARANG BARU (Data Master)
# Gunakan ini untuk mendaftarkan barang baru ke sistem pertama kali
POST http://localhost:5000/api/barang
Content-Type: application/json

{
    "nama_barang": "Papan Akrilik",
    "kategori": "Bahan Cetak",
    "stok": 0,
    "satuan": "Pcs"
}

###

### 2. MELIHAT DAFTAR SEMUA BARANG
GET http://localhost:5000/api/barang

###

# ==========================================
# (PENTING: Copy ID Barang dari respons GET di atas lalu letakkan di "barangId" di bawah ini)
# ==========================================

### 3. MENCATAT BARANG MASUK (Menambah Stok)
POST http://localhost:5000/api/transaksi/masuk
Content-Type: application/json

{
    "barangId": "69e4f6230b8f4a373811f2c6", 
    "jumlah": 10,
    "keterangan": "Stok awal dari gudang"
}

###

### 4. MENCATAT BARANG KELUAR (Mengurangi Stok)
POST http://localhost:5000/api/transaksi/keluar
Content-Type: application/json

{
    "barangId": "69e4f6230b8f4a373811f2c6",
    "jumlah": 2,
    "keterangan": "Fakultas Ekonomi dan Bisnis memesan papan akrilik 2 untuk mencetak keperluan mereka"
}

###

### 5. MELIHAT RIWAYAT BARANG MASUK
GET http://localhost:5000/api/transaksi/masuk

###

### 6. MELIHAT RIWAYAT BARANG KELUAR
GET http://localhost:5000/api/transaksi/keluar
